<?xml version="1.0" encoding="UTF-8"?>
<TestRun id="4e524f08-209c-47b8-b0cf-c4284452909a" name="fora@DELL 2015-08-18 02:16:34" runUser="dell\fora" xmlns="http://microsoft.com/schemas/VisualStudio/TeamTest/2010">
  <TestSettings name="Local" id="ae7f9b34-cdf6-4f5e-886b-aeb8da462ab8">
    <Description>These are default test settings for a local test run.</Description>
    <Deployment enabled="false" runDeploymentRoot="fora_DELL 2015-08-18 02_16_34">
      <DeploymentItem filename="B:\студия\Курсы C#\Task4\Data\Contacts\Contacts\Contacts\bin\Debug\Contacts.exe" />
    </Deployment>
    <Execution>
      <TestTypeSpecific />
      <AgentRule name="Execution Agents">
      </AgentRule>
    </Execution>
  </TestSettings>
  <Times creation="2015-08-18T02:16:34.0734476+06:00" queuing="2015-08-18T02:16:34.1145127+06:00" start="2015-08-18T02:16:34.1205183+06:00" finish="2015-08-18T02:16:34.4327387+06:00" />
  <ResultSummary outcome="Failed">
    <Counters total="1" executed="1" error="0" failed="1" timeout="0" aborted="0" inconclusive="0" passedButRunAborted="0" notRunnable="0" notExecuted="0" disconnected="0" warning="0" passed="0" completed="0" inProgress="0" pending="0" />
  </ResultSummary>
  <TestDefinitions>
    <UnitTest name="ChangeCardSynCodeTest_CheckSynCodeIsNegativeException" storage="b:\студия\курсы c#\task4\data\contacts\contacts\unittest\bin\debug\unittest.dll" id="19074d93-ae85-cada-5799-e2c8a2c8421c">
      <Execution id="2594e6f3-5bff-4d5e-9f82-91d925fca32c" />
      <TestMethod codeBase="B:/студия/Курсы C#/Task4/Data/Contacts/Contacts/Unittest/bin/Debug/Unittest.DLL" adapterTypeName="Microsoft.VisualStudio.TestTools.TestTypes.Unit.UnitTestAdapter, Microsoft.VisualStudio.QualityTools.Tips.UnitTest.Adapter, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" className="Unittest.CardTest, Unittest, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" name="ChangeCardSynCodeTest_CheckSynCodeIsNegativeException" />
    </UnitTest>
  </TestDefinitions>
  <TestLists>
    <TestList name="Results Not in a List" id="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
    <TestList name="All Loaded Results" id="19431567-8539-422a-85d7-44ee4e166bda" />
  </TestLists>
  <TestEntries>
    <TestEntry testId="19074d93-ae85-cada-5799-e2c8a2c8421c" executionId="2594e6f3-5bff-4d5e-9f82-91d925fca32c" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
  </TestEntries>
  <Results>
    <UnitTestResult executionId="2594e6f3-5bff-4d5e-9f82-91d925fca32c" testId="19074d93-ae85-cada-5799-e2c8a2c8421c" testName="ChangeCardSynCodeTest_CheckSynCodeIsNegativeException" computerName="DELL" duration="00:00:00.0350411" startTime="2015-08-18T02:16:34.1225183+06:00" endTime="2015-08-18T02:16:34.4187488+06:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Failed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="2594e6f3-5bff-4d5e-9f82-91d925fca32c">
      <Output>
        <ErrorInfo>
          <Message>Test method Unittest.CardTest.ChangeCardSynCodeTest_CheckSynCodeIsNegativeException did not throw expected exception System.ArgumentException. Сервис не вернул сообщение об ошибке при обновлении у карточки поля SynCode отрицательным значением</Message>
        </ErrorInfo>
      </Output>
    </UnitTestResult>
  </Results>
</TestRun>